namespace: <namespace>
bases:
  - ../../base
  - ../../../frontend/overlays/development
  - ../../../redis-master/overlays/development
  - ../../../redis-slave/overlays/development

commonAnnotations:
  git-sha: <git-sha>
  git-branch: <git-branch>
  git-link: <git-link>
