name: checkout without persist-credentials
on:
  pull_request:
    branches: ["main"]

jobs:
  checkout:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # default is true. Set to false to avoid persisting the token in git config.
          persist-credentials: false

      - name: fetch default branch should fail
        run: |
          if ! git fetch ${{ github.event.repository.default_branch }}; then
            echo "✔️ fetch failed as expected"
          else
            echo "❌ fetch succeeded unexpectedly"
            exit 1
          fi

      # If you need to do git operations, you need to set git remote again
      - name: set git remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: fetch default branch should work
        run: git fetch ${{ github.event.repository.default_branch }}

      # Delete git config to avoid affecting other steps
      - name: Remove git config
        if: always()
        run: |
          git remote rm origin
          git config unset --global user.email
          git config unset --global user.name
