name: checkout without persist-credentials
on:
  pull_request:
    branches: ["main"]

jobs:
  checkout:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # default is true. Set to false to avoid persisting the token in git config.
          persist-credentials: false

      - name: tag setup
        run: git tag test-auth-checkout

      - name: verify credentials are not persisted
        run: |
          if ! git push origin test-auth-checkout; then
            echo "✔️ push tag failed as expected due to missing credentials"
          else
            echo "❌ push tag succeeded unexpectedly, credentials were persisted"
            git push --delete origin test-auth-checkout
            exit 1
          fi

      # If you need to do git operations, you need to set git remote again
      - name: set git remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push and delete test tag to confirm auth
        run: |
          git push origin test-auth-checkout
          git push --delete origin test-auth-checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Delete git config to avoid affecting other steps
      - name: Remove git config
        if: always()
        run: |
          git remote rm origin
          git config unset --global user.email
          git config unset --global user.name
