name: git sparse checkout (disable cone)
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sparse-checkout:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          sparse-checkout: |
            src/*
          sparse-checkout-cone-mode: false # required for ! entry to work
          persist-credentials: false
      - name: list root folders
        run: ls -la
      - name: list src folders
        run: ls -laR ./src
