# name: "github api sample"
# on:
#   issues:
#     types: [opened]

# jobs:
#   comment:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/github-script@v1
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.addLabels({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               labels: ["hoge"]
#             })
