name: permissions minimum
on:
  pull_request:
    branches: ["main"]

jobs:
  check-permissions:
    # specify minimum permissions as possible
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - name: Check job permissions
        run: echo "permissions ${CONTEXT}"
        env:
          CONTEXT: ${{ toJson(job.permissions) }}
      # checkout
      # build
