name: skip ci pr title

on: ["pull_request"]

jobs:
  skip:
    if: "!(contains(github.event.pull_request.title, '[skip ci]') || contains(github.event.pull_request.title, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo $TITLE
        env:
          TITLE: ${{ toJson(github.event.pull_request.title) }}

  build:
    runs-on: ubuntu-latest
    needs: skip
    steps:
      - run: echo run when not skipped
